### PR TITLE
add requirements.txt for handling dependencies.

### PR DESCRIPTION
**Pull request by SanketDG**
Instead of just listing out all the dependencies, you could just put them in a `requirements.txt` file and then instruct users to:

`pip install -r requirements.txt`

I wasn't sure, how you would like to put this message in the README, so I left that for you.

### CODE REVIEW

**Comment by msikma** [comment]
Thanks, I do need to make a requirements.txt file... this script was made way back when I didn't know about dependency management in Python.

**Comment by SanketDG** [comment]
So will this get merged?

**Comment by msikma** [comment]
Oh, my bad for looking at a PR late at night. I actually thought you were making an issue, not a PR. That's why I said "I need to make a requirements file" even though you already made it. :)

I'll check and merge this tomorrow.

**Comment by msikma** [comment]
Thanks for your contribution. I went and did some refactoring of the code as well.

**Comment by SanketDG** [comment]
Thanks!

**Pull request merged**
